# Generated by Django 5.2.11 on 2026-02-17 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='schools/thumbnails/')),
                ('name', models.CharField(max_length=255)),
                ('website_link', models.URLField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('location_link', models.URLField(blank=True, max_length=500)),
                ('mail', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('funding_type', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('hybrid', 'Hybrid')], default='public', max_length=20)),
                ('education_level', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('high_school', 'High school'), ('college', 'College')], default='primary', max_length=20)),
                ('teaching_language', models.CharField(choices=[('bilingual', 'Bilingual'), ('french_mission', 'French Mission'), ('spanish_mission', 'Spanish Mission'), ('other', 'Other')], default='bilingual', max_length=30)),
                ('teaching_language_other', models.CharField(blank=True, max_length=100)),
                ('university_name', models.CharField(blank=True, max_length=255)),
                ('keywords', models.CharField(blank=True, max_length=255)),
                ('rating', models.DecimalField(decimal_places=1, default=4.0, max_digits=2)),
                ('review_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
