# Generated by Django 4.2.28 on 2026-03-03 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_sample_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='acceptance_rate',
            field=models.CharField(blank=True, help_text='e.g. XX.XX%', max_length=50),
        ),
        migrations.AddField(
            model_name='school',
            name='ai_recommendation',
            field=models.TextField(blank=True, help_text='AI recommendation bullet points, one per line'),
        ),
        migrations.AddField(
            model_name='school',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed information about the school'),
        ),
        migrations.AddField(
            model_name='school',
            name='job_acceptance_rate',
            field=models.CharField(blank=True, help_text='e.g. XX.XX%', max_length=50),
        ),
        migrations.AddField(
            model_name='school',
            name='programs',
            field=models.CharField(blank=True, help_text='Comma-separated programs/majors', max_length=500),
        ),
        migrations.AddField(
            model_name='school',
            name='ranking',
            field=models.CharField(blank=True, help_text='e.g. #X', max_length=50),
        ),
        migrations.AddField(
            model_name='school',
            name='recommended_for',
            field=models.CharField(blank=True, help_text='e.g. Recommended for technicians', max_length=255),
        ),
        migrations.AddField(
            model_name='school',
            name='sentiment_score',
            field=models.DecimalField(decimal_places=1, default=0.0, help_text='Percentage 0-100', max_digits=4),
        ),
        migrations.AddField(
            model_name='school',
            name='student_count',
            field=models.CharField(blank=True, help_text='e.g. XX student', max_length=50),
        ),
        migrations.AddField(
            model_name='school',
            name='tuition',
            field=models.CharField(blank=True, help_text='e.g. XX.XX$', max_length=50),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='Anonymous', max_length=100)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='schools.school')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
