# Generated by Django 4.2.28 on 2026-03-18 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_school_acceptance_rate_school_ai_recommendation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='sentiment',
            field=models.CharField(blank=True, choices=[('good', 'Good'), ('bad', 'Bad'), ('neutral', 'Neutral')], default='neutral', help_text='LLM-classified sentiment: good, bad, or neutral', max_length=10),
        ),
    ]
