# Generated by Django 4.2.28 on 2026-03-27 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_comment_sentiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='administration_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='affordability_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='facilities_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='teachers_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='school',
            name='administration_score',
            field=models.FloatField(default=0.0, help_text='Average administration aspect score'),
        ),
        migrations.AddField(
            model_name='school',
            name='affordability_score',
            field=models.FloatField(default=0.0, help_text='Average affordability aspect score'),
        ),
        migrations.AddField(
            model_name='school',
            name='facilities_score',
            field=models.FloatField(default=0.0, help_text='Average facilities aspect score'),
        ),
        migrations.AddField(
            model_name='school',
            name='teachers_score',
            field=models.FloatField(default=0.0, help_text='Average teachers aspect score'),
        ),
    ]
