# Generated by Django 6.0.2 on 2026-02-27 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id_analysis', models.AutoField(primary_key=True, serialize=False)),
                ('polarity', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'analysis',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Aspect',
            fields=[
                ('id_aspect', models.AutoField(primary_key=True, serialize=False)),
                ('aspect_name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'aspect',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id_choice', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'choice',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id_comment', models.AutoField(primary_key=True, serialize=False)),
                ('data_source', models.CharField(blank=True, max_length=255, null=True)),
                ('comment_date', models.DateTimeField(blank=True, null=True)),
                ('comment_content', models.TextField()),
                ('sentiment_score', models.FloatField(blank=True, null=True)),
                ('sentiment_label', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'comment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MotCle',
            fields=[
                ('id_mot_cle', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=50)),
                ('id_school', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mot_cle',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PersonalityTest',
            fields=[
                ('id_test', models.AutoField(primary_key=True, serialize=False)),
                ('criteria', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'personality_test',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ResponseTest',
            fields=[
                ('id_response', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'response_test',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id_school', models.AutoField(primary_key=True, serialize=False)),
                ('school_name', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=500)),
                ('image', models.TextField(blank=True, null=True)),
                ('financial_type', models.TextField()),
                ('education_type', models.TextField()),
                ('university_name', models.CharField(blank=True, max_length=200, null=True)),
                ('teaching_language', models.CharField(max_length=100)),
                ('website_link', models.TextField(blank=True, null=True)),
                ('maps_link', models.TextField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'school',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SchoolComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ecole', models.IntegerField()),
            ],
            options={
                'db_table': 'school_comment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SchoolSpeciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'school_speciality',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SessionTest',
            fields=[
                ('id_session', models.AutoField(primary_key=True, serialize=False)),
                ('id_utilisateur', models.IntegerField()),
                ('date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'session_test',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id_speciality', models.AutoField(primary_key=True, serialize=False)),
                ('speciality_name', models.TextField()),
            ],
            options={
                'db_table': 'speciality',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id_question', models.AutoField(primary_key=True, serialize=False)),
                ('question_content', models.TextField()),
            ],
            options={
                'db_table': 'test_question',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=150, unique=True)),
                ('role', models.TextField(blank=True, null=True)),
                ('prenom', models.CharField(blank=True, max_length=100, null=True)),
                ('nom', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
