# Generated by Django 6.0.1 on 2026-02-25 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0002_seed_questions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aspect',
            options={'verbose_name': 'Aspect', 'verbose_name_plural': 'Aspects'},
        ),
        migrations.RemoveConstraint(
            model_name='answerchoice',
            name='unique_question_text',
        ),
        migrations.RemoveConstraint(
            model_name='aspectscore',
            name='unique_session_aspect',
        ),
        migrations.RemoveConstraint(
            model_name='useranswer',
            name='unique_session_question',
        ),
        migrations.RenameIndex(
            model_name='useranswer',
            new_name='preferences_session_06d756_idx',
            old_name='preferences_sess_idx',
        ),
        migrations.RenameIndex(
            model_name='useranswer',
            new_name='preferences_questio_2a8a4f_idx',
            old_name='preferences_quest_idx',
        ),
        migrations.RenameIndex(
            model_name='userpreferenceprofile',
            new_name='preferences_complet_4eb5dd_idx',
            old_name='preferences_comp_idx',
        ),
        migrations.RenameIndex(
            model_name='userpreferencesession',
            new_name='preferences_user_id_4b1ec6_idx',
            old_name='preferences_user_crea_idx',
        ),
        migrations.AlterUniqueTogether(
            name='answerchoice',
            unique_together={('question', 'text')},
        ),
        migrations.AlterUniqueTogether(
            name='aspectscore',
            unique_together={('session', 'aspect')},
        ),
        migrations.AlterUniqueTogether(
            name='useranswer',
            unique_together={('session', 'question')},
        ),
        migrations.AddIndex(
            model_name='aspectscore',
            index=models.Index(fields=['session', 'aspect'], name='preferences_session_c514ee_idx'),
        ),
    ]
